export const donationsContent = {
  newContribution: {
    tabs: {
      finance: "Financeira",
      food: "Alimentos",
    },
    sections: {
      finance: "Financeiras",
      food: "Alimentícias",
    },
    actions: {
      submit: "Cadastrar",
      submitting: "Enviando...",
    },
    pointsLabel: "Pontuação",
  },
  financialForm: {
    eventLabel: "Nome do Evento / Doador",
    eventPlaceholder: "Ex: Instituto Alma",
    goalLabel: "Meta (R$)",
    goalPlaceholder: "Ex: R$100",
    expensesLabel: "Gastos (R$)",
    expensesPlaceholder: "Ex: R$100",
    amountLabel: "Valor Arrecadado",
    amountPlaceholder: "Ex: R$100",
    receiptLabel: "Comprovante (PNG/JPEG/PDF)",
    receiptButtonAria: "Selecionar comprovante",
    receiptAlt: "Selecionar comprovante",
    receiptEmpty: "Nenhum arquivo escolhido",
  },
  foodForm: {
    eventLabel: "Nome do Evento",
    eventPlaceholder: "Ex: Instituto Alma",
    goalLabel: "Meta",
    goalPlaceholder: "100 Kg",
    expensesLabel: "Gastos",
    expensesPlaceholder: "Ex: R$100",
    totalKgLabel: "Total em Kg",
    columns: {
      food: "Alimento",
      units: "Unidades",
      kgPerUnit: "Kg/Unidade",
    },
    selectPlaceholder: "Selecione um alimento",
    quantityPlaceholder: "Qtd",
    kgPlaceholder: "Kg",
    receiptLabel: "Imagem dos Alimentos (PNG/JPEG/PDF)",
    receiptAlt: "Selecionar comprovante",
    receiptEmpty: "Nenhum arquivo escolhido",
  },
  foodOptions: [
    { id: 1, nome: "Arroz Polido" },
    { id: 2, nome: "Feijão Preto" },
    { id: 3, nome: "Leite em Pó" },
    { id: 4, nome: "Óleo de Soja" },
    { id: 5, nome: "Açúcar Refinado" },
    { id: 6, nome: "Fubá" },
    { id: 7, nome: "Macarrão" },
    { id: 8, nome: "Outros" },
  ],
  foodPointsPerKg: {
    "Arroz Polido": 4,
    "Feijão Preto": 5.5,
    "Açúcar Refinado": 4,
    "Leite em Pó": 15,
    Fubá: 2.5,
    Macarrão: 2.5,
    "Óleo de Soja": 7,
    Outros: 0,
  } as Record<string, number>,
  errors: {
    invalidFileType: "Formato inválido. Use PNG, JPEG ou PDF.",
    invalidFileSize: "Arquivo muito grande (máx. 5MB).",
    missingFood: "Selecione um alimento válido.",
    missingFinancial:
      "Preencha todos os campos obrigatórios da contribuição financeira.",
    missingFoodFields:
      "Preencha todos os campos obrigatórios da contribuição alimentícia.",
    saveFinancial: "Erro ao cadastrar contribuição financeira:",
    saveFood: "Erro ao cadastrar contribuição alimentícia:",
  },
  success: {
    financial: "Contribuição financeira cadastrada com sucesso!",
    food: "Contribuição alimentícia cadastrada com sucesso!",
  },
  allDonations: {
    eventPlaceholder: "Nome do evento",
    createError: "Erro ao cadastrar contribuição",
    createSuccess: "Contribuição registrada com sucesso!",
    connectionError: "Erro de conexão com o servidor.",
  },
};
