export const profilesContent = {
  user: {
    emailMentorLabel: "Email Mentor",
    emailMentorPlaceholder: "Adicione aqui o Mentor de seu time!",
    emailMentorSubmitAlt: "Salvar mentor",
    addMentorSuccess: "Mentor adicionado com sucesso!",
    addMentorError: "Ocorreu um erro ao salvar o mentor.",
    invalidEmail: "Por favor, insira um email válido.",
    saveMentorError: "Erro ao salvar o mentor no banco de dados.",
    teamNameFallback: "Nome do time aparecerá aqui",
    classPrefix: "Turma",
    classFallback: "X",
    studentMentorLabel: "Aluno-Mentor",
    studentMentorFallback: "Nome do Usuario aparecerá aqui",
    membersLabel: "Integrantes do grupo",
    membersFallback: "RAs dos alunos aparecerão aqui",
    heroTitle: "Arkana +\nLideranças Empáticas",
  },
  admin: {
    profileTitle: "Perfil do Administrador",
    addAdminTitle: "Cadastre abaixo um novo administrador ao Arkana:",
    addAdminDescription:
      "Ele terá os mesmos acessos que você, como o histórico de contribuições de todos os grupos!",
    emailLabel: "Email do novo administrador:",
    emailPlaceholder: "NovoAdministrador@gmail.com",
    passwordLabel: "Senha do novo administrador:",
    passwordPlaceholder: "Senha do novo administrador",
    submit: "Cadastrar",
    invalidEmail: "Por favor, insira um email válido.",
    fetchAdminError: "Erro ao buscar dados do mentor",
    saveAdminError: "Erro ao salvar novo admin no banco de dados.",
    saveAdminSuccess: "Mentor adicionado com sucesso!",
  },
};
